name: Build

on: [push]
jobs:
  build:
    runs-on: toaster
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false
      - name: Build with Gradle
        run: ./gradlew build

      - name: Capture Build Artifacts
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/