name: Build

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Artifacts
          path: build/libs/
